apiVersion: apps/v1
kind: Deployment
metadata:
  name: redjar-test-app
  labels:
    app: redjar
spec:
  replicas: 3
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: redjar
  template:
    metadata:
      labels:
        app: redjar
      annotations:
        force-sync: "2025-07-10-16-59"
    spec:
      containers:
        - name: redjar-container
          image: asantar0/redjar-test-app:b9a19bd
          ports:
          - containerPort: 3000
          env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
      imagePullSecrets:
      - name: regcred
