name: Build image and push to DockerHub

on:
  push:
    branches:
      - main
    paths:
      - 'manifests/**'

permissions:
  contents: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set image tag (short commit SHA)
        id: vars
        run: echo "TAG=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            asantar0/redjar-test-app:latest
            asantar0/redjar-test-app:${{ steps.vars.outputs.TAG }}

      - name: Update deployment.yaml with new image tag
        run: |
          sed -i "s|image: asantar0/redjar-test-app:.*|image: asantar0/redjar-test-app:${{ steps.vars.outputs.TAG }}|" manifests/deployment.yaml

      - name: Create deployment hash file
        run: |
          echo "${{ steps.vars.outputs.TAG }}" > .deployment-hash
          echo "Deployment hash: ${{ steps.vars.outputs.TAG }}"
          echo "Hash saved to .deployment-hash file"

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add manifests/deployment.yaml
          git commit -m "Update deployment image tag to ${{ steps.vars.outputs.TAG }}"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
